apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cert-manager-webhook-cloudns.fullname" . }}:cloudns-api-secret-access
  labels:
    app: {{ include "cert-manager-webhook-cloudns.name" . }}
rules:
  - apiGroups: [""]
    resources:
      - secrets
    resourceNames:
      - {{ .Values.secretName }}
    verbs:
      - 'get'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cert-manager-webhook-cloudns.fullname" . }}:api-secret-access
  labels:
    app: {{ include "cert-manager-webhook-cloudns.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cert-manager-webhook-cloudns.fullname" . }}:api-secret-access
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    namespace: default
    name: {{ include "cert-manager-webhook-cloudns.fullname" . }}
