apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-manager-webhook-cloudns.fullname" . }}
  labels:
    app: {{ include "cert-manager-webhook-cloudns.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: {{ include "cert-manager-webhook-cloudns.name" . }}
